baseUrl = 'https://fences.wallet.ng'

new_transaction = "/transactions/new"
transaction_details = "/details"
list_providers = "/bills/airtime/providers"
buy_airtime = "/bills/airtime/purchase"
list_bank = "/transfer/banks/all"
account_enquiry = "/transfer/bank/account/enquire"
account_transfer = "/transfer/bank/account"
transfer_details = "/transfer/bank/details"
list_categories = "/bills/providers"
list_billers = "/bills/providers/{0}/billers"
list_payment_items = "/bills/providers/biller/{0}/items"
bill_validation = "/bills/validate"
pay_bill = "/bills/pay"
charge_wallet = "/wallet/charge"
credit_wallet = "/wallet/credit"
get_balance = "/wallet/balance"
create_wallet = "/wallet/create"

AUTH_HEADER = "Bearer {0}"
